spring:
    application:
        name: auth-service
    datasource:
        url: jdbc:mysql://localhost:3307/authservice
        username: root
        password: Sharvan623!@
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
server:
    port: 8080

    